#! /usr/bin/env bash

if [[ $# != 0 ]]
then
  echo "Usage: $(basename $0) <overlay>"
  echo ""
  echo "Diff the given overlay for the current kubectl context."
  exit 1
fi

kubectl diff -k k8s/$(kubectx -c) | delta
